Feature/sandbox
bitzlato/baseapp pull request #136
Opened 2021-09-12 10:15 UTC by mailer21

2021-09-12 13:48 UTC, trzmaxim requested changes
@mailer21 Если это финальные изменения, которые пойдут в мастер, то исправь пожалуйста заголовки этого PR и коммитов.

У нас есть гайд как это делать правильно: [bitzlato/guides#как-правильно-делать-commit-ы](https://github.com/bitzlato/guides#%D0%BA%D0%B0%D0%BA-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-commit-%D1%8B)

Например просто `Add deploy sandbox`
И два коммита лучше объединить 🙏

2021-09-12 18:07 UTC, mailer21 commented
> @mailer21 
> И два коммита лучше объединить 🙏

done

2021-09-12 18:13 UTC, trzmaxim approved these changes

2021-09-13 04:23 UTC, dapi requested changes

2021-09-13 04:23 UTC, dapi commented on config/deploy/sandbox.rb
> +set :public_url, "https://#{ENV.fetch( 'SANDBOX_SERVER' )}/"
SANDBOX_SERVER -> SANDBOX_HOST

2021-09-13 05:27 UTC, mailer21 commented on config/deploy/sandbox.rb
> +set :public_url, "https://#{ENV.fetch( 'SANDBOX_SERVER' )}/"
> SANDBOX_SERVER -> SANDBOX_HOST

done

2021-09-13 13:34 UTC, dapi approved these changes

2021-09-13 13:34 UTC, merged