Switch on dynamic modules
bitzlato/baseapp pull request #140
Opened 2021-09-14 08:59 UTC by c0gnize

- изменена опция module с commonjs на amd
- `tsconfig-paths` нужен для компиляции `development.ts` файлов отличным от tsconfig.json файлом
- удален cache-loader и thread-loader т.к. мешали генерации чанков

2021-09-14 09:11 UTC, trzmaxim commented on web/tsconfig.webpack.json
> +{
А для чего нам несколько конфигов? Почему нельзя использовать один?

2021-09-14 09:11 UTC, trzmaxim commented on web/tsconfig.json
> +        "module": "amd",
Почему amd?

2021-09-14 09:12 UTC, c0gnize commented on web/tsconfig.json
> +        "module": "amd",
предлагай

2021-09-14 09:13 UTC, c0gnize commented on web/tsconfig.webpack.json
> +{
в описании написал же

2021-09-14 09:15 UTC, c0gnize commented on web/tsconfig.webpack.json
> +{
чтобы конфиг файл development.ts собирать другой конфигурацией, а то amd не принимает

2021-09-14 09:16 UTC, trzmaxim commented on web/tsconfig.json
> +        "module": "amd",
Прости, я просто не понимаю для чего нужно это изменение. Мне интересно какие даст улучшения/изменения в итоге.
Я думаю, раз ты принял это решение – значит разобрался в вопросе и прошу тебя поделиться опытом 🙏

2021-09-14 09:18 UTC, trzmaxim commented on web/tsconfig.webpack.json
> +{
А что случилось такого что он перестал принимать `development.ts`? Сейчас как-то не так работает?
Я не понимаю проблемы.

2021-09-14 09:20 UTC, trzmaxim commented on web/tsconfig.webpack.json
> +{
А понял. Ты решил использовать amd. И тут проблема с development.ts 👌

2021-09-14 09:24 UTC, c0gnize commented
Сори, надо было яcнее написать. Сейчас генерируется один большой бандл. Чтобы динамические импорты действительно импортили отдельные модули, включил amd. Из-за этого перестал запускаться webpack, т.к. используется tsconfig.json и он работает только с commonjs, поэтому добавил новый tsconfig.webpack.json :)

2021-09-14 09:31 UTC, c0gnize commented on web/tsconfig.json
> +        "module": "amd",
в принципе тут можно наверно вставить что-то посовременне вставить, сейчас попробую

2021-09-14 17:27 UTC, trzmaxim requested changes

2021-09-15 06:39 UTC, c0gnize commented on web/webpack/development.ts
>                              reloadAll: true,
можно, но это повлечет гораздно больше изменений

2021-09-15 06:55 UTC, c0gnize commented on web/webpack/development.ts
>                              reloadAll: true,
хотя вроде можно обойтись без tsconfig-paths другим путем

2021-09-15 08:23 UTC, trzmaxim commented on web/webpack/development.ts
>                              reloadAll: true,
Для какого-то конфига столько боли 😫

2021-09-15 08:24 UTC, trzmaxim approved these changes
👍

2021-09-15 08:25 UTC, merged