Feature: add Fees screen
bitzlato/baseapp pull request #182
Opened 2021-10-04 17:03 UTC by c0gnize

<img width="1045" alt="Screenshot 2021-10-04 at 19 57 41" src="https://user-images.githubusercontent.com/12247182/135892735-d933d33b-c3b6-438b-acd3-46164c68714a.png">

2021-10-04 21:34 UTC, trzmaxim requested changes
А почему ты начал использовать префиксы в названии коммитов?
Если есть такое желание можем следовать https://www.conventionalcommits.org/en/v1.0.0/ и использовать semantic-release 😃

2021-10-04 21:34 UTC, trzmaxim commented on web/src/screens/Fees/index.tsx
> +      <div className="cr-row cr-row-spacing">
Давай не будем использовать глобальные имена классов. Я считаю наша цель избавиться от это практики. Компоненты должны быть изолированы.

2021-10-04 21:34 UTC, trzmaxim commented on web/src/screens/Fees/index.tsx
> +  const data = currencies.map((d) => {
Почему d? Как выбираешь сокращение?
Это плохая практика сокращать имена до одной буквы или до не информативного набора букв

2021-10-04 21:34 UTC, trzmaxim commented on web/src/screens/Fees/index.tsx
> +        <CurrencyIcon currency={d.id} icon={d.icon_url} iconId={d.icon_id} size="small" />
Вот у этого компонента пропсы `iconId` и `icon`, оба могу вывести иконку, но `icon` почему-то приоритетнее. Как это понять не заглядывая в реализацию компонента? Это наводит на мысль, что компоненте ошибка.

Я предлагаю сделать компонент который отразит иконку от объекта Currency
`<CurrencyIcon currency={currency} />` и не нужно беспокоится о тонкостях  `iconId` и `icon`

2021-10-05 06:34 UTC, c0gnize commented
> А почему ты начал использовать префиксы в названии коммитов? Если есть такое желание можем следовать https://www.conventionalcommits.org/en/v1.0.0/ и использовать semantic-release 😃

Предыдущие два коммита брал из upstream, поэтому были с префиксами. А что, давай будем следовать этой конвенции :)

2021-10-05 06:36 UTC, c0gnize commented on web/src/components/CryptoCurrencyIcon/CryptoCurrencyIcon.postcss
> +    width: 36px !important;
Только не в этом PR

2021-10-05 06:45 UTC, c0gnize commented on web/src/components/CryptoCurrencyIcon/CryptoCurrencyIcon.tsx
> +      className={cn('cr-wallet-item__single__image-icon', sizeClassName)}
Да

2021-10-05 06:46 UTC, c0gnize commented on web/src/components/CryptoCurrencyIcon/CryptoCurrencyIcon.tsx
> +export const CurrencyIcon: FC<CurrencyIconProps> = ({ currency, icon, iconId, size }) => {
Второй компонент в этом файле нигде не используется, я его содержимое сюда просто перенесу

2021-10-05 06:46 UTC, c0gnize commented on web/src/containers/Footer/Footer.tsx
> +              <Link to="/fees" className={s.link}>
👍

2021-10-05 06:49 UTC, c0gnize commented on web/src/index.pcss
> +  --rgap: 0.5rem;
Интересная ситуация внутри заголовка таблицы произошла. Там шрифт меньше и из-за em отступ слева соответственно меньше получался, выглядело некрасиво. Вообще не понимаю, зачем к em привязываться

2021-10-05 06:53 UTC, c0gnize commented on web/src/screens/Fees/index.tsx
> +  const data = currencies.map((d) => {
d -> datum, это у меня из использования d3 пришло. Когда эта буква одно в функции, читать же намного проще, многобуквенное название, в данном случае currency, просто будет раздувать тело фунции, соответсвенно и читать дольше

2021-10-05 06:54 UTC, c0gnize commented on web/src/screens/Fees/index.tsx
> +        <CurrencyIcon currency={d.id} icon={d.icon_url} iconId={d.icon_id} size="small" />
Я этот компонент просто перенес из другого места в более общее, разве не ты сам его добавлял?

2021-10-05 07:23 UTC, c0gnize commented on web/src/components/CryptoCurrencyIcon/CryptoCurrencyIcon.postcss
> +  &--medium img {
Нормальная практика, используется кучей людей и все живы
- аргумент, но на практике, ты написал классы, использовал их в компоненте, и забыл про них
- на моей практике кучи вложенностей я не встречал, обычно два уровня, реже три. Это здесь, в baseapp, вложенность зашкаливает и в целом организация стилей плохая

Лично для меня стиль имени мало волнует, главное чтобы структуру видеть.

2021-10-05 08:42 UTC, trzmaxim commented on web/src/components/CryptoCurrencyIcon/CryptoCurrencyIcon.postcss
> +.iconMedium img,
👍

2021-10-05 08:55 UTC, c0gnize commented on web/src/screens/Fees/index.tsx
> +      <div className="cr-row cr-row-spacing">
Какой толк от изолированности если это ведет только к увеличению одинакого кода? Зачем мне каждый раз добавлять повторяющиеся классы для одних и тех же нужд? Можно вынести эти классы в отдельный файл и импортировать из оттуда, обернуть в компонент. Но ради достижения чего?

2021-10-05 09:20 UTC, trzmaxim approved these changes
👍

2021-10-05 09:20 UTC, merged