fix: show amount error during the editing (EX-127)
bitzlato/baseapp pull request #283
Opened 2021-12-16 13:04 UTC by c0gnize

- show amount error during the editing
- reset market price
- use currency precision instead of the market's price_precision

https://bitzlato.atlassian.net/browse/EX-127

https://user-images.githubusercontent.com/12247182/146401348-1320989a-65f2-4f7e-ae8c-a912394dc097.mov

2021-12-16 17:26 UTC, trzmaxim requested changes

2021-12-16 17:26 UTC, trzmaxim commented on web/src/components/MoneyFormat/MoneyFormat.tsx
> +  noColor?: boolean;
`noColor` ничего не говорит в контексте `MoneyFormat` и не расширяемый. Что будет если понадобиться какой-то `secondary` цвет?
Считаю, что должен быть более расширяемый проп, например `variant` или `textColor`

2021-12-16 17:26 UTC, trzmaxim commented on web/src/containers/QuickExchange/AmountDescription.tsx
> +  if (props.market && props.fromWallet && props.toWallet && props.price.request_price) {
Почему не делаешь деструктуризацию объекта `props`?

2021-12-16 17:26 UTC, trzmaxim commented on web/src/containers/QuickExchange/AmountDescription.tsx
> +export const AmountDescription: React.FC<AmountDescriptionProps> = (props) => {
А это получается валидатор формы в рендере компонента? А так точно надо? 
Обычно же валидируют в onChange, сохраняют ошибку в стейт, выводят ошибку.

2021-12-17 07:59 UTC, c0gnize commented on web/src/containers/QuickExchange/AmountDescription.tsx
> +export const AmountDescription: React.FC<AmountDescriptionProps> = (props) => {
в onChange еще не все даннные для валидации готовы, поэтому так

2021-12-17 08:59 UTC, trzmaxim approved these changes

2021-12-17 08:59 UTC, merged