#241 Replaced the Decimal component with the AmountFormat
bitzlato/baseapp pull request #315
Opened 2022-01-26 07:32 UTC by vsemkov

2022-01-26 07:55 UTC, c0gnize commented on web/src/components/AmountFormat/AmountFormat.tsx
> +  prevValue?: Money;
не надо менять AmountFormat, надо завести новый компонент, типа `DiffAmountFormat`

2022-01-26 07:55 UTC, c0gnize commented on web/src/components/AmountFormat/AmountFormat.tsx
> +import { handleHighlightValue } from 'src/containers/RecentTrades/Market';
эту функцию надо вынести src/helpers и она должна возвращать не react компоненты, а два значения `[match, diff]`

2022-01-26 08:24 UTC, trzmaxim requested changes

2022-01-26 08:24 UTC, trzmaxim commented on web/src/mobile/components/Orders/OrdersItem.tsx
> +              с
Опечатка?

2022-01-27 06:27 UTC, c0gnize commented
- при именовании коммитов мы следуем https://www.conventionalcommits.org/en/v1.0.0/, поэтому в твоем случае коммиты будут начинаться с `chore:`
- rebase от мастера надо сделать, конфликты есть

2022-01-27 06:29 UTC, c0gnize commented on web/src/components/TickerTable/index.tsx
> +      const CCY = createCcy('',  market.price_precision);
это же просто переменная, поэтому `ccy`

2022-01-27 14:13 UTC, vsemkov commented on web/src/mobile/components/Orders/OrdersItem.tsx
> +              с
спасибо, опечатка исправлю

2022-01-28 10:09 UTC, c0gnize commented on web/src/mobile/components/Orders/OrdersItem.tsx
> +              <AmountFormat money={createMoneyWithoutCcy(filled, FIXED_VOL_PRECISION)} color={setTradeColor(order.side).color} />
можно заменить на:
```
<Box textColor={order.side === 'buy' ? 'bid' : 'ask'}>
     <AmountFormat money={createMoney(filled, createCcy('', FIXED_VOL_PRECISION))} />
</Box>
```
тогда и изменение в AmountFormat не нужно будет

2022-01-28 10:09 UTC, c0gnize commented on web/src/helpers/money.ts
> +export function formatWithSeparators(value: string, thousSep?: string, floatSep?: string) {
для чего эта функция? кажется лишней

2022-01-28 10:09 UTC, c0gnize commented on web/src/components/DiffAmountFormat/DiffAmountFormat.tsx
> +  const higlightedValue = handleHighlightValue(currentValue.toFormat(options), prevValue?.toFormat(options), );
`?` лишнее + лишняя запятая в функции

2022-01-28 10:09 UTC, c0gnize commented on web/src/helpers/handleHighlightValue.ts
> +export const handleHighlightValue = (curValue: string, prevValue: string): [string, string] => {
название не очень удачное

2022-01-29 10:02 UTC, vsemkov commented on web/src/helpers/money.ts
> +export function formatWithSeparators(value: string, thousSep?: string, floatSep?: string) {
Использовалась в containers/Order/index.tsx, заменил на 

        message: [
          this.translate('error.order.create.available', {
           - available: formatWithSeparators(String(available), ','),
           + available: createMoneyWithoutCcy(String(available), currentMarket.amount_precision).toFormat(),
            currency:
              type === 'buy'
                ? currentMarket.quote_unit.toUpperCase()
                : currentMarket.base_unit.toUpperCase(),
          }),

в верное ли значение precision?

2022-01-29 10:03 UTC, vsemkov commented on web/src/mobile/components/Orders/OrdersItem.tsx
> +              <AmountFormat money={createMoneyWithoutCcy(filled, FIXED_VOL_PRECISION)} color={setTradeColor(order.side).color} />
ок

2022-01-31 09:35 UTC, c0gnize commented
@vsemkov сори, тебе опять придется сделать rebase

2022-01-31 10:03 UTC, c0gnize commented on web/src/helpers/money.ts
> +export function formatWithSeparators(value: string, thousSep?: string, floatSep?: string) {
не могу сказать насчет верности, но пока сойдет

2022-02-01 08:41 UTC, c0gnize approved these changes
👍

2022-02-01 08:41 UTC, c0gnize commented
@trzmaxim дело за тобой)

2022-02-01 08:42 UTC, trzmaxim approved these changes

2022-02-01 08:42 UTC, merged