feat: Change QuickExchange component (EX-130)
bitzlato/baseapp pull request #334
Opened 2022-02-04 08:36 UTC by vsemkov

2022-02-04 10:03 UTC, c0gnize commented
- cделай rebase, тесты починил
- хорошо бы приложить скрин, чтобы увидеть результат

2022-02-04 10:07 UTC, trzmaxim requested changes

2022-02-04 10:07 UTC, trzmaxim commented on web/src/components/Spoiler/Spoiler.postcss
> +}
Настрой редактор, чтобы использовались `.editorconfig` и `.prettierrc` для форматирования кода.

2022-02-04 11:27 UTC, trzmaxim commented on web/src/components/Spoiler/index.tsx
> +          <>{title}</>
Для чего фрагмент?

2022-02-04 11:27 UTC, trzmaxim commented on web/src/components/Spoiler/index.tsx
> +export const Spoiler = React.memo(SpoilerComponent);
Точно нужно `React.memo`? Объясни свою мотивацию.

Я считаю, что в компоненте нет сложных вычислений и можно без `React.memo`

2022-02-04 11:27 UTC, trzmaxim commented on web/src/components/Spoiler/index.tsx
> +import React from 'react';
C React 17 не нужен импорт
```suggestion
import { memo } from 'react';
```

2022-02-04 11:27 UTC, trzmaxim commented on web/src/containers/QuickExchange/QuickExchange.postcss
> +}
Файл без final newline. Форматируй его с помощью prettier.

2022-02-04 11:27 UTC, trzmaxim commented on web/src/containers/QuickExchange/QuickExchange.tsx
> +  const Limits = () =>
Я считаю, оборачивать в функцию излишне. Что думаешь?

2022-02-04 11:27 UTC, trzmaxim commented on web/src/containers/QuickExchange/QuickExchange.tsx
> +          variant=""
Думаю что это не верно оставлять его пустым.

2022-02-04 11:37 UTC, trzmaxim commented on web/src/components/WalletList/__snapshots__/WalletList.test.tsx.snap
> +
Из-за этого изменения тест со напшотом упал

2022-02-04 11:46 UTC, vsemkov commented on web/src/components/WalletList/__snapshots__/WalletList.test.tsx.snap
> +
это поправил.

2022-02-04 13:30 UTC, trzmaxim commented on web/src/components/Spoiler/index.tsx
> +import { Accordion } from 'react-bootstrap';
Пожалуйста, не используй index файлы для реализации компонентов. Переименуй в `Spoiler.tsx`

2022-02-04 15:16 UTC, c0gnize commented
@vsemkov приложи плиз в описание PR скрины

2022-02-04 15:20 UTC, vsemkov commented
<img width="485" alt="Снимок экрана 2022-02-04 в 14 22 45" src="https://user-images.githubusercontent.com/934634/152554465-ee0a3950-6ac8-4b9b-80aa-a85001e331a2.png">
<img width="780" alt="Снимок экрана 2022-02-04 в 14 16 23" src="https://user-images.githubusercontent.com/934634/152554486-31c3009d-a938-4e15-8f24-b32fa1ca6f4b.png">

2022-02-04 15:41 UTC, c0gnize commented
Для эстетичноости
- кнопку перестановки лучше сдвинуть правее, а курс выровнить с ним по вертикали
- линию под Лимиты выровнить с линией под Быстрый обмен

2022-02-04 15:41 UTC, c0gnize commented on web/src/assets/icons/QuestionIcon.tsx
> +export const QuestionIcon: FC<JSX.IntrinsicElements['svg']> = (props) => {
нигде не используется, зачем нужна?

2022-02-04 15:41 UTC, c0gnize commented on web/src/components/Spoiler/ToggleButton/ToggleButton.postcss
> +  transition: 0.2s linear;
это точно нужно?

2022-02-04 15:41 UTC, c0gnize commented on web/src/components/Spoiler/Spoiler.tsx
> +import { ToggleButton } from './ToggleButton/ToggleButtom';
Файл можно и не помещать в отдельую директорию ToggleButton

2022-02-04 15:41 UTC, c0gnize commented on web/src/components/Spoiler/Spoiler.tsx
> +export const Spoiler = ({ title, children }: Props) => {
`export const Spoiler: FC<Props> = ({ title, children }) => {` тогда и children не надо определять в Props

2022-02-04 15:41 UTC, c0gnize commented on web/src/components/Spoiler/ToggleButton/ToggleButtom.tsx
> +  callback?: (value: string) => void;
callback вообще планируется использовать?

2022-02-04 15:41 UTC, c0gnize commented on web/src/containers/QuickExchange/QuickExchange.tsx
> +        <Box col align="start" className={s.quickExchangeLimit}>
а давай использовать флаг `isMobileDevice` 
- будет более явно
- не будет рендера лишних элементов

2022-02-07 10:22 UTC, c0gnize approved these changes

2022-02-07 10:23 UTC, trzmaxim approved these changes

2022-02-07 10:23 UTC, merged