Deeplinks 181171392
bitzlato/baseapp pull request #388
Opened 2022-02-24 01:08 UTC by vikseriq

2022-03-01 13:35 UTC, trzmaxim commented on web/src/hooks/useT.ts
> +export const useBetterT = (): TranslateWithCallbackFn => {
Давай не будем добавлять новые варианты для функций переводов. Это может стать дополнительной проблемой при рефакторинге системы переводов.

2022-03-17 19:03 UTC, trzmaxim requested changes

2022-03-17 19:03 UTC, trzmaxim commented on web/src/screens/DeepLinkPreview/DeepLinkPreview.tsx
> +  };
Я считаю, не нужно делать функций для рендера. В этом случаем можно обойтись let переменной
```suggestion
  let actions;
    switch (formAction) {
      case DeeplinkActionType.LoginRequired:
        actions = (
          <Button color="primary" onClick={() => loginWithRedirect()}>
            {t('common.action.sign_in_up')}
          </Button>
        );
        break;
      case DeeplinkActionType.AcceptOrCancel:
        actions = (
          <Box
            display="flex"
            justifyContent="space-between"
            flexDirection={{ mobile: 'column', tablet: 'row' }}
          >
            <Button color="primary" variant="outlined" onClick={onDiscard}>
              {t('common.action.discard')}
            </Button>
            <Button color="primary" variant="contained" onClick={onAccept}>
              {t('common.action.accept')}
            </Button>
          </Box>
        );
        break;
      case DeeplinkActionType.NoAction:
        break;
      case DeeplinkActionType.Dismiss:
      default:
        actions = (
          <Button color="primary" onClick={onDismiss}>
            OK
          </Button>
        );
        break;
    }
```

2022-03-17 19:22 UTC, vikseriq commented on web/src/routes/Layout/index.tsx
> +            { commonRoutes }
Надо унифицировать, по другим частям кода eslint грозно прошелся с принуждением расставить пробелы.

2022-03-18 00:15 UTC, vikseriq commented on web/src/screens/DeepLinkPreview/DeepLinkPreview.tsx
> +    fetch(`${p2pUrl()}/deeplink/`, {
`use-mutation` и реализации – это хуки. Нам же нужно выполнить действие по условию во вложенной функции, если реализовать в виде `useAcceptVoucherDeeplink` то нарушится RoH.

2022-03-18 00:30 UTC, vikseriq commented on web/src/screens/DeepLinkPreview/DeepLinkPreview.tsx
> +      return <pre>Error: {JSON.stringify(isError)}</pre>;
Текст ошибки в заголовке из `deeplinkTitle`, этого достаточно.

2022-03-18 08:44 UTC, trzmaxim commented on web/src/screens/DeepLinkPreview/DeepLinkPreview.tsx
> +export const DeepLinkPreview: () => JSX.Element = () => {
```suggestion
export const DeepLinkPreview: FC = () => {
```

2022-03-18 08:47 UTC, trzmaxim commented on web/src/components/DeepLinkInfo/DeepLinkInfo.tsx
> +            <p className={sprinkles({ color: 'danger' })}>
Я думал ты догадаешься. Не нужно использовать sprinkles напрямую здесь. Используй `web/src/components/ui/Box`.

2022-03-18 08:49 UTC, trzmaxim commented on web/src/routes/Layout/index.tsx
> +            { commonRoutes }
Можешь убрать этот файл с .eslintignore и исправить ошибки

2022-03-18 08:53 UTC, trzmaxim commented on web/src/screens/DeepLinkPreview/DeepLinkPreview.tsx
> +    fetch(`${p2pUrl()}/deeplink/`, {
Прости, что такое RoH?

Используй use-mutation, он создаст тебе функцию, которую ты после можешь использовать в этой вложенной функции. И его стейт может тебе полностью заменить `ActionResult`

2022-03-23 07:11 UTC, trzmaxim requested changes

2022-03-23 07:11 UTC, trzmaxim commented on web/src/components/DeepLinkInfo/index.tsx
> +import { FC } from 'react';
Не создавай index файлы с реализацией чего-либо

2022-03-23 07:11 UTC, trzmaxim commented on web/src/components/DeepLinkInfo/index.tsx
> +export const useDeeplinkInfo = (deeplinkId: string) => {
Перенеси в отдельный файл в web/src/hooks/data

2022-03-23 07:11 UTC, trzmaxim commented on web/src/components/index.ts
> +export * from './Card/Card';
В челом лучше забить на эти index файлы и импортировать напрямую

2022-03-23 07:11 UTC, trzmaxim commented on web/src/hooks/useT.ts
> +) => string;
это уже не актуально?

2022-03-23 07:11 UTC, trzmaxim commented on web/src/components/DeepLinkInfo/VoucherInfo.tsx
> +const activateVoucher: (voucherCode: string) => ActivationResult = async (voucherCode) => {
```suggestion
const activateVoucher = async (voucherCode: string): Promise<ActivationResult> => {
```

2022-03-23 09:50 UTC, vikseriq commented on web/src/components/DeepLinkInfo/index.tsx
> +import { FC } from 'react';
Переименовано в `DeepLinkInfo.tsx`

2022-03-23 16:32 UTC, trzmaxim commented on web/src/components/ui/index.ts
> +export * from './Text';
Неееет) Не надо так делать, ни каких index файлов, все импорты на прямую, плиз :)

2022-03-23 17:07 UTC, trzmaxim approved these changes

2022-03-23 18:10 UTC, merged