fix: Changed and fixed TransferHistory, added Spinner and no-data [#181199535]
bitzlato/baseapp pull request #408
Opened 2022-03-11 10:43 UTC by vsemkov

2022-04-12 08:13 UTC, trzmaxim requested changes

2022-04-12 08:13 UTC, trzmaxim commented on web/src/containers/Wallets/TransferHistory.tsx
> +import { Spinner } from 'react-bootstrap';
```suggestion
import { Spinner } from 'web/src/components/ui/Spinner';
```

2022-04-12 08:13 UTC, trzmaxim commented on web/src/containers/Wallets/TransferHistory.tsx
> +          : vars.colors.secondary;
А это разве сработает? В итоге нужны имена цветов `success` `warning` `secondary`, чтобы использовать так `<Box color="warning">`

2022-04-12 09:29 UTC, vsemkov commented on web/src/theme/vars.css.ts
> +    secondary: colors.silverChaliceLight,
Я посмотрел значение rgb цвета в pcss переменных и исходя из значений добавил в новые, так как аналог не нашел. С названием согласен, переименую.

2022-04-13 12:44 UTC, trzmaxim requested changes

2022-04-13 12:44 UTC, trzmaxim commented on web/src/containers/Wallets/TransferHistory.tsx
> +  size?: 'small' | 'wide' | undefined;
```suggestion
  size?: 'small' | 'large' | undefined;
```

2022-04-13 13:25 UTC, trzmaxim approved these changes

2022-04-13 13:26 UTC, c0gnize approved these changes

2022-04-13 13:28 UTC, merged