chore: Profile block account [#181148307]
bitzlato/baseapp pull request #413
Opened 2022-03-17 15:12 UTC by vsemkov

2022-03-17 15:32 UTC, trzmaxim requested changes

2022-03-17 15:32 UTC, trzmaxim commented on web/src/components/profile/settings/FreezeAccount.tsx
> +      <Modal size="lg" show={open} onClose={handleClose}>
```suggestion
      <Modal size="sm" show={open} onClose={handleClose}>
```
Поменяй размер, будет ближе к дизайну

2022-03-17 15:32 UTC, trzmaxim commented on web/src/components/profile/settings/FreezeAccount.tsx
> +        <ModalFooter>
```suggestion
```
Нужно убрать, лишняя обёртка и отступы лишние даёт.

2022-03-17 15:32 UTC, trzmaxim commented on web/src/components/profile/settings/ProfileSettings.tsx
> +            <FreezeAccount />
Перемести кнопку в другой блок, чтобы как по дизайну было 
https://github.com/bitzlato/baseapp/blob/master/web/src/components/profile/Profile.tsx#L52
![Снимок экрана 2022-03-17 в 18 22 23](https://user-images.githubusercontent.com/2435004/158834040-45b70d34-879c-4749-8c90-0a85f37bb14b.png)

2022-03-17 16:23 UTC, trzmaxim requested changes

2022-03-17 16:23 UTC, trzmaxim commented on web/src/custom/translations/ru.ts
> +    'operations <strong>will be suspended</strong>!',
Добавь перевод на русский

2022-03-21 19:50 UTC, trzmaxim requested changes

2022-03-21 19:50 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +import { Spinner } from 'react-bootstrap';
Используй `web/src/components/ui/Spinner`, от react-bootstrap нужно уходить

2022-03-21 19:50 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +      reset();
Объясни, пожалуйста, для чего нужно сразу вызывать `reset`?

2022-03-21 19:50 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +  const handleFreeze = () => freezeAccount();
```suggestion
  const handleClickFreeze = () => freezeAccount();
```

2022-03-21 19:50 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +      <Button color="secondary" disabled={!!isSelfFrozen} onClick={handleClick}>
```suggestion
      <Button color="secondary" disabled={isSelfFrozen} onClick={handleClick}>
```

2022-03-21 19:50 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +export const FreezeAccount: FC<{ isSelfFrozen?: boolean | undefined }> = ({ isSelfFrozen }) => {
```suggestion
export const FreezeAccount: FC<{ isSelfFrozen?: boolean | undefined }> = ({ isSelfFrozen = false }) => {
```

2022-03-21 19:50 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +            <Box display="flex" alignItems="center" justifyContent="center" px="6x" py="20x">
для чего `px="6x"` если и так всё по центру выравниваешь?

2022-03-21 19:50 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +            <Box display="flex" alignItems="center" justifyContent="center" px="6x" py="20x">
да и `alignItems="center"` вроде не нужен

2022-03-21 19:50 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +                {t('Yes')}
Давай поменяем на "Заблокировать"

2022-03-21 19:50 UTC, trzmaxim commented on web/src/modules/user/profile/types.ts
> +    self_frozen?: boolean;
```suggestion
    self_frozen: boolean;
```
Это свойство обязательное

2022-03-21 19:50 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +                <a href={t('Support Link')} target="_blank" rel="noopener noreferrer">
`href={t('Support Link')}` почему так?

2022-03-21 19:52 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +export const FreezeAccount: FC<{ isSelfFrozen?: boolean | undefined }> = ({ isSelfFrozen }) => {
`isSelfFrozen` не может быть `undefined`. От бэка всегда приходит это свойство, написал об этом ниже.

2022-03-22 07:51 UTC, vsemkov commented on web/src/components/profile/FreezeAccount.tsx
> +      reset();
Правильно, нужно выводить ошибку и кнопку "Закрыть", но так как все ошибки появляются сверху, остается только вариант с сбросить состояние и дать возможность пользователю попробовать снова заблокировать аккаунт, просто закрыть окно после неудачи, будет непонятен результат. Если есть предложения, давай обсудим.

2022-03-22 07:54 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +      reset();
Считаю, что не нужно ничего делать дополнительно при ошибке, только ошибку в алерте выводить

2022-03-22 08:00 UTC, vsemkov commented on web/src/components/profile/FreezeAccount.tsx
> +                <a href={t('Support Link')} target="_blank" rel="noopener noreferrer">
Исправил.

2022-03-22 08:00 UTC, vsemkov commented on web/src/modules/user/profile/types.ts
> +    self_frozen?: boolean;
ок!

2022-03-22 13:59 UTC, trzmaxim requested changes

2022-03-22 13:59 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +export const FreezeAccount: FC<{ isSelfFrozen: boolean }> = ({ isSelfFrozen }) => {
```suggestion
interface Props { 
  isSelfFrozen: boolean;
}

export const FreezeAccount: FC<Props> = ({ isSelfFrozen }) => {
```

2022-03-22 13:59 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +import { Spinner } from '../ui/Spinner';
```suggestion
import { Spinner } from 'web/src/components/ui/Spinner';
```

2022-03-22 13:59 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +  }knowledgebase/`;
```suggestion
import { getBitzlatoLink } from 'web/src/components/shared/Footer/Footer';
  const supportLink = getBitzlatoLink(currentLanguage, 'knowledgebase');
```

2022-03-22 13:59 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +  const getModalContent = () => {
Я считаю, если тебе пришлось делать функцию для рендера, то нужно вынести это в отдельный компонент. Либо используй let переменные

2022-03-22 13:59 UTC, trzmaxim commented on web/src/components/profile/Profile.tsx
> +          <FreezeAccount isSelfFrozen={user.bitzlato_user?.user_profile.self_frozen || false} />
```suggestion
          {user.bitzlato_user && <FreezeAccount isSelfFrozen={user.bitzlato_user.user_profile.self_frozen} />}
```

2022-03-23 07:17 UTC, trzmaxim requested changes

2022-03-23 07:17 UTC, trzmaxim commented on web/src/custom/translations/ru.ts
> +  'page.body.profile.header.account.content.twoFactorAuthentication.message.enabled': 'Включен',
Кстати эта правка не нужна

2022-03-23 07:17 UTC, trzmaxim commented on web/src/hooks/mutations/useUpdateProfile.ts
> +export const useFreezeProfile = () => {
Вынеси в отдельный файл, пожалуйста

2022-03-23 07:29 UTC, vsemkov commented on web/src/custom/translations/ru.ts
> +  'page.body.profile.header.account.content.twoFactorAuthentication.message.enabled': 'Включен',
ок, верну. Но этот ключ есть в профайле.

2022-03-23 07:29 UTC, vsemkov commented on web/src/hooks/mutations/useUpdateProfile.ts
> +export const useFreezeProfile = () => {
сделаю.

2022-03-23 07:33 UTC, trzmaxim commented on web/src/components/profile/FreezeAccount.tsx
> +          )}
```suggestion
              <Button color="secondary" fullWidth disabled={status === 'running'} onClick={handleClickFreeze}>
                {t('Freeze')}
              </Button>
              <Box w="4x" flexShrink={0} />
```
лучше просто кнопку блокировать, иначе скачет кнопка "закрыть" не красиво

2022-03-24 11:48 UTC, trzmaxim approved these changes

2022-03-24 11:56 UTC, merged