fix: add some improvements to Gifts [#181695481]
bitzlato/baseapp pull request #439
Opened 2022-03-28 13:16 UTC by c0gnize

- Писать так же сумму Примерно в фиате
- Кнопки % (25,50,75,100) должны брать сумму от фиата, а не от крипты
- В созданном/обналиченном чеках писать валюту, в которой был создан, а не в USD
- Добавить информативности на две ошибки: нельзя выписать чек в фиате меньше 1 ,а больше чем на кошельке.
- При вводе суммы в фиате - показывать сколько это эквивалентно в крипте

![Screenshot 2022-03-28 at 15 14 05](https://user-images.githubusercontent.com/12247182/160406057-829650f4-14ee-4439-bb21-9132e762edf6.png)

2022-03-28 13:34 UTC, trzmaxim requested changes

2022-03-28 13:34 UTC, trzmaxim commented on web/src/containers/Gift/Gift.tsx
> +  const rateResponse = useFetch<CurrencyRate>(
Сделай отдельный хук. Будет удобнее если потребуется переиспользовать

2022-03-29 06:06 UTC, c0gnize commented on web/src/containers/Gift/Gift.tsx
> +  const rateResponse = useFetch<CurrencyRate>(
+

2022-03-29 06:19 UTC, trzmaxim commented on web/src/containers/Gift/Gift.tsx
> +  const rateResponse = useFetch<CurrencyRate>(
что значит точка?

2022-03-29 06:30 UTC, c0gnize commented on web/src/containers/Gift/Gift.tsx
> +  const rateResponse = useFetch<CurrencyRate>(
я плюс поставил, а получилась точка

2022-03-29 06:34 UTC, trzmaxim approved these changes

2022-03-29 06:38 UTC, merged