feat: Add reset password request [181148307]
bitzlato/baseapp pull request #442
Opened 2022-03-29 10:51 UTC by vsemkov

2022-03-29 10:59 UTC, trzmaxim requested changes

2022-03-29 10:59 UTC, trzmaxim commented on web/src/components/profile/Profile.tsx
> +          {user.bitzlato_user && <ChangePassword email={user.bitzlato_user?.email} />}
```suggestion
          {user.bitzlato_user && <ChangePassword email={user.bitzlato_user.email} />}
```
У тебя и так проверка есть

2022-03-29 10:59 UTC, trzmaxim commented on web/src/components/profile/ChangePassword.tsx
> +  }, [data.status]);
Это можно в `onSuccess` в `useMutation` передать через `useChangePassword`

2022-03-31 09:35 UTC, c0gnize commented
А как это соотносится с уже существующей `Forgot password?` на странице /signin?

2022-03-31 09:39 UTC, trzmaxim approved these changes

2022-03-31 09:43 UTC, c0gnize commented
Увидел, что тот же запрсо дергается

2022-03-31 09:44 UTC, trzmaxim commented
Да, это так

2022-03-31 09:55 UTC, c0gnize commented
Я что-то не вижу отрисовки captcha, точно на проде будет работать?

2022-03-31 10:05 UTC, trzmaxim commented
Точно, требует капчу :(

2022-04-01 07:47 UTC, merged