feat: Improving Deeplinks [#181171392]
bitzlato/baseapp pull request #455
Opened 2022-04-01 12:06 UTC by vikseriq

feat: Restyle Deeplinks with Sprinkles.
feat: Add non user dismissible modal.

2022-04-01 12:13 UTC, trzmaxim requested changes

2022-04-01 12:13 UTC, trzmaxim commented on web/src/components/DeepLinkInfo/VoucherInfo.tsx
> +    totalCrypto: <b>{`${payload.amount} ${payload.cc_code}`}</b>,
Должно быть `strong` вместо `b`

2022-04-01 12:13 UTC, trzmaxim commented on web/src/components/ui/Modal.tsx
> +    if (persistent) {
Для чего это?

2022-04-01 12:16 UTC, trzmaxim commented on web/src/screens/DeepLinkPreview/DeepLinkPreview.tsx
> +    <Modal size="lg" show persistent>
А мы точно хотим чтобы это было как модалка?

2022-04-01 12:18 UTC, trzmaxim commented on web/src/screens/DeepLinkPreview/DeepLinkPreview.tsx
> +    <Modal size="lg" show persistent>
Модалка есть, а на фоне ничего 🤔

2022-04-08 13:12 UTC, vikseriq commented on web/src/components/ui/Modal.tsx
> +    if (persistent) {
Модалки, требующие действия, которые нельзя закрыть случайно щёлкнув вне или по esc.

2022-04-08 13:13 UTC, trzmaxim commented on web/src/components/ui/Modal.tsx
> +    if (persistent) {
нам сейчас это разве нужно?

2022-04-08 14:37 UTC, trzmaxim commented on web/src/components/DeepLinkInfo/VoucherInfo.tsx
> +              onClick={() => openExternalLink(botLink.url)}
А для чего так? Почему нельзя сделать сразу ссылку?

2022-04-08 15:16 UTC, trzmaxim approved these changes

2022-04-11 09:06 UTC, merged