Feature/p2p notification 181866263
bitzlato/baseapp pull request #484
Opened 2022-04-21 10:54 UTC by velsamm

2022-04-25 17:34 UTC, trzmaxim requested changes

2022-04-26 11:03 UTC, velsamm commented on web/src/components/Header/notificationInfo.ts
> +    //   };
хороший вопрос. я не знаю.
в п2п это не обрабатывается никто. подозреваю, что данная нотификация не используется (либо, что маловероятно, выпилена)

2022-04-26 16:16 UTC, trzmaxim commented on web/src/components/Header/notificationInfo.ts
> +        currencyamount: formatFiatWithDelimiters(item.data.currency.amount, 2),
Используй форматирование из `@bitzlato/money-js`

2022-04-26 16:16 UTC, trzmaxim commented on web/src/components/Header/notificationInfo.ts
> +        text: t('mute', { duration: parseInt(item.data.duration) }),
```suggestion
        text: t('mute', { duration: parseInt(item.data.duration, 10) }),
```
и игнорирование eslint можно убрать

2022-04-27 07:52 UTC, trzmaxim commented on web/src/components/Header/notificationInfo.ts
> +        }).toString(),
```
import { getFormatOptionsByLanguage } from 'web/src/components/AmountFormat/getFormatOptionsByLanguage';
```
```suggestion
        currencyamount: Money.fromDecimal(item.data.currency.amount, {
          code: item.data.currency.code,
          minorUnit: 2,
        }).toFormat({ ...getFormatOptionsByLanguage(lang) }),
```

2022-04-27 08:07 UTC, trzmaxim approved these changes

2022-04-27 08:10 UTC, trzmaxim commented
Для начала выглядит терпимо, потом будем улучшать.
@c0gnize ты будешь смотреть или мержим?

2022-04-27 08:12 UTC, c0gnize commented
> Для начала выглядит терпимо, потом будем улучшать. @c0gnize ты будешь смотреть или мержим?

балиин, я забыл закомментить :(

2022-04-27 08:13 UTC, c0gnize commented
у меня только к formatFiatWithDelimiters была претензия, остальные стилистические, принимаю

2022-04-27 08:14 UTC, c0gnize approved these changes

2022-04-27 08:22 UTC, velsamm commented on web/src/components/Header/notificationInfo.ts
> +function formatFiatWithDelimiters(value: number, maximumFractionDigits: number): string | number {
да. изначально взял с п2п эту функцию. потом убрал

2022-04-27 11:05 UTC, merged