feat: Added Trader block [181865584]
bitzlato/baseapp pull request #506
Opened 2022-04-27 15:18 UTC by vsemkov

2022-04-28 08:10 UTC, trzmaxim requested changes

2022-04-28 08:10 UTC, trzmaxim commented on web/src/components/ui/Stack.tsx
> +  childFullWidth,
Используй Box, а эти изменения отмени

2022-04-28 08:10 UTC, trzmaxim commented on web/src/components/ui/ToggleButton.tsx
> +      color={active ? color : 'block'}
Используй доработки из master

2022-04-28 08:10 UTC, trzmaxim commented on web/src/components/ui/Button.css.ts
> +      icon: sprinkles({
А это отставляем 👍

2022-04-28 08:10 UTC, trzmaxim commented on web/src/components/ui/ToggleButton.tsx
> +export const ToggleButton: FC<ToggleButtonProps> = ({
Компонент не нужен, стейты держи в других компонентах.

2022-04-28 08:10 UTC, trzmaxim commented on web/src/theme/vars.css.ts
> +    blockSecond: colors.white5,
```suggestion
    traderNotesBg: colors.white5,
```

2022-05-11 11:36 UTC, c0gnize commented
Сделай плиз Resolve conversation для запросов Максима, если исправил

2022-05-11 11:38 UTC, c0gnize reviewed
Зачем две одинаковые иконки FavoriteIcon и FavoriteStatusIcon?

2022-05-11 11:45 UTC, c0gnize commented on web/src/components/Trader/Chat.css.ts
> +export const chatButton = style({
не используется

2022-05-11 11:45 UTC, c0gnize commented on web/src/components/Trader/Chat.tsx
> +                Равным образом постоянный количественный рост и сфера нашей активности представляет
я так понимаю это потом удалится?

2022-05-11 11:45 UTC, c0gnize commented on web/src/routes/Layout/index.tsx
> +          <PrivateRoute
надо перенести выше под условие `process.env.REACT_APP_RELEASE_STAGE === 'development'`

2022-05-11 11:45 UTC, c0gnize commented on web/src/translations/en.ts
> +  'trader.block.showAll': 'Show all',
Давай такие простые сочетания заводить напрямую: `'Show all': 'Show all'`

2022-05-16 06:34 UTC, c0gnize commented
@vsemkov поправь пожалуйста быстрее и залей в мастер

2022-05-16 19:58 UTC, vsemkov commented on web/src/components/Trader/Chat.tsx
> +                Равным образом постоянный количественный рост и сфера нашей активности представляет
конечно!

2022-05-17 06:46 UTC, c0gnize commented
> Зачем две одинаковые иконки FavoriteIcon и FavoriteStatusIcon?

@vsemkov, не ответил

2022-05-17 06:50 UTC, c0gnize approved these changes

2022-05-17 06:50 UTC, c0gnize commented on web/src/components/trader/Trader.css.ts
> +  marginLeft: '8px',
думаю тут sizeVars надо использовать

2022-05-17 06:50 UTC, c0gnize commented on web/src/components/IconButton/IconButton.tsx
> +  size?: 'small' | 'icon' | undefined;
лишнее изменение?

2022-05-17 06:50 UTC, c0gnize commented on web/src/custom/translations/ru.ts
> +  'trader.block.tabChat': 'чат',
с большой буквы наверно надо - `Чат`

2022-05-17 06:50 UTC, c0gnize commented on web/src/screens/Trader/index.tsx
> +      <Trader publicName="Smart_Trade" />
публичное имя можно сразу из урла вытягивать

2022-05-24 10:16 UTC, vsemkov commented
> Зачем две одинаковые иконки FavoriteIcon и FavoriteStatusIcon?  Удалил FavoriteStatusIcon.

2022-05-24 10:20 UTC, c0gnize approved these changes

2022-05-24 10:23 UTC, c0gnize commented
ошибки линтера надо тольк починить

2022-05-24 17:21 UTC, c0gnize commented
@vsemkov когда будешь мержить?

2022-05-25 07:20 UTC, trzmaxim requested changes

2022-05-25 07:20 UTC, trzmaxim commented on web/src/components/shared/Trader/Trader.tsx
> +import { TraderInfo } from '../../traderInfo/TraderInfo';
```suggestion
import { TraderInfo } from 'web/src/components/traderInfo/TraderInfo';
```

2022-05-25 11:46 UTC, trzmaxim approved these changes

2022-05-25 12:15 UTC, merged