Fix/shared header redesign [#182071688]
bitzlato/baseapp pull request #523
Opened 2022-05-16 16:02 UTC by YuriFA

2022-05-23 05:55 UTC, c0gnize approved these changes

2022-05-23 05:55 UTC, c0gnize commented on web/src/components/shared/Header/BackButton.css.ts
> +  fontSize: 17,
по хорошему надо из vars тянуть эту константу

2022-05-30 15:08 UTC, YuriFA commented
Задеплоено на s (baseapp), s1 (p2p-ssr)

2022-05-31 08:53 UTC, trzmaxim requested changes
очень много, посмотрел только часть

2022-05-31 08:53 UTC, trzmaxim commented on web/src/components/shared/Header/Drawer/Drawer.tsx
> +    window.addEventListener('scroll', handleScroll);
А для производительности не нужно троттлить обработку?

2022-05-31 08:53 UTC, trzmaxim commented on web/src/components/shared/Header/Dropdown/DropdownItem.css.ts
> +    // bg: 'dropdownItemHover',
```suggestion
```
можешь удалить

2022-05-31 08:53 UTC, trzmaxim commented on web/src/components/shared/Header/Navigation.tsx
> +      item.tabs.findIndex((tab) => tab.to === pathname || pathname.indexOf(tab.to) > -1) > -1,
```suggestion
      item.tabs.some((tab) => tab.to === pathname || pathname.startsWith(tab.to)),
```
Думаю с `startsWith` будет лучше совпадение. Нам же не нужно совпадение путей где-то по середине?

2022-05-31 08:53 UTC, trzmaxim commented on web/src/components/shared/Header/NavigationItem.css.ts
> +    // px: '6x',
```suggestion
```

2022-05-31 08:53 UTC, trzmaxim commented on web/src/components/shared/Header/NavigationTabs.css.ts
> +    zIndex: 99990,
нужно в `vars.css.ts` положить в `zIndexVars`

2022-05-31 08:53 UTC, trzmaxim commented on web/src/components/shared/Header/NavigationTabs.css.ts
> +    fontSize: 16,
тоже нужно в vars.css.ts положить

2022-05-31 08:53 UTC, trzmaxim commented on web/src/components/shared/Header/NavigationItem.tsx
> +  const { focusWithinProps } = useFocusWithin({
Ого, а объясни зачем это нужно, можешь голосом, если будет проще :)

2022-05-31 08:53 UTC, trzmaxim commented on web/src/components/shared/Header/Navigation.tsx
> +  const [nextTabToOpen, setNextTabToOpen] = useState<null | string>(null);
А для чего нужен `nextTabToOpen`?

2022-05-31 08:55 UTC, trzmaxim commented on web/src/custom/translations/ru.ts
> +  'AD Board': 'Маркет',
А почему Маркет ? :)

2022-05-31 09:03 UTC, YuriFA commented on web/src/components/profile/ProfileSwitchAccount.tsx
> -        borderColor="dropdownBorder"
По дизайну у дропдауна бордера не было, вот и убрал цвет, соответственно и сам бордер тут

2022-05-31 10:26 UTC, YuriFA commented on web/src/custom/translations/ru.ts
> +  'AD Board': 'Маркет',
Попросили заменить, тк в мобилке плохо отображается меню (не видно что можно скролить)

2022-05-31 10:53 UTC, trzmaxim requested changes

2022-05-31 10:53 UTC, trzmaxim commented on web/src/components/shared/Header/BackButton.css.ts
> +  fontSize: 'tabTitle',
Не, в sprinkles не нужно было добавлять, там там много `conditions` – это сгенерирует большое количество кода, а тут одноразовое использование, по-этому нужно так:

```
import { headerFontSizes } from 'vars.css.ts';

export const button = style({
  fontSize: headerFontSizes.navigationItem,
```

2022-05-31 11:22 UTC, trzmaxim commented on web/src/components/shared/Header/Navigation.tsx
> +  const [nextTabToOpen, setNextTabToOpen] = useState<null | string>(null);
Разобрались, пусть так будет

2022-05-31 11:23 UTC, trzmaxim commented on web/src/components/shared/Header/NavigationItem.tsx
> +  const { focusWithinProps } = useFocusWithin({
Разобрались

2022-05-31 11:36 UTC, trzmaxim approved these changes

2022-05-31 11:36 UTC, trzmaxim commented
👍

2022-05-31 11:47 UTC, merged