fix: Add filter path params to ads filter [#181865520]
bitzlato/baseapp pull request #545
Opened 2022-05-26 14:02 UTC by YuriFA

Добавил параметры фильтра в виде url: /board/type-cryptocurrency-currency?other-filter-params

<img width="727" alt="image" src="https://user-images.githubusercontent.com/10403829/170503301-7adca912-659c-4a83-a402-1db52d51ad59.png">

2022-05-26 14:35 UTC, c0gnize approved these changes

2022-05-26 14:35 UTC, c0gnize commented on web/src/components/shared/Ads/Board.tsx
> +  useEffect(() => {
а это точно надо? если открыли без filter то пусть так и остается

2022-05-26 14:38 UTC, YuriFA commented on web/src/components/shared/Ads/Board.tsx
> +  useEffect(() => {
Это на случай когда currency или cryptocurrency нет в списке, или ввели типа с ошибкой /board/buy-btc-fkdsjfkds

2022-05-26 14:40 UTC, YuriFA commented on web/src/components/shared/Ads/Board.tsx
> +  useEffect(() => {
Ой, не про то предыдущее написал. Это поведение как в p2p просто

2022-05-27 08:48 UTC, trzmaxim requested changes

2022-05-27 08:48 UTC, trzmaxim commented on web/src/components/shared/Ads/Board.tsx
> +  return Boolean(type && (type === 'buy' || type === 'sell'));
```suggestion
  return type === 'buy' || type === 'sell';
```
Такой проверки достаточно

2022-05-27 08:48 UTC, trzmaxim commented on web/src/components/shared/Ads/Board.tsx
> +    currency: currency?.toUpperCase() || DEFAULT_FILTER.currency,
```suggestion
    cryptocurrency: cryptocurrency?.toUpperCase() ?? DEFAULT_FILTER.cryptocurrency,
    currency: currency?.toUpperCase() ?? DEFAULT_FILTER.currency,
```

2022-05-27 08:48 UTC, trzmaxim commented on web/src/components/shared/Ads/Board.tsx
> +    type: isSeoType(seoType) ? seoTypeToAd[seoType] : DEFAULT_FILTER.type,
```suggestion
    type: seoTypeToAd[seoType] ?? DEFAULT_FILTER.type,
```
Можно вовсе без проверки `isSeoType`

2022-05-27 08:48 UTC, trzmaxim commented on web/src/components/shared/Ads/Board.tsx
> +            upd.currency || filterParams.currency,
```suggestion
            upd.type ?? filterParams.type,
            upd.cryptocurrency ?? filterParams.cryptocurrency,
            upd.currency ?? filterParams.currency,
```

2022-05-27 08:48 UTC, trzmaxim commented on web/src/components/shared/Ads/Board.tsx
> +    if (!cryptoCurrencies.find((currency) => currency.code === filterParams.cryptocurrency)) {
```suggestion
    if (!cryptoCurrencies.some((currency) => currency.code === filterParams.cryptocurrency)) {
```

или

```suggestion
    if (cryptoCurrencies.every((currency) => currency.code !== filterParams.cryptocurrency)) {
```

2022-05-27 09:17 UTC, YuriFA commented on web/src/components/shared/Ads/Board.tsx
> +    type: isSeoType(seoType) ? seoTypeToAd[seoType] : DEFAULT_FILTER.type,
seoType может быть undefined, а ts не даст в индекс вставлять undefined

2022-05-27 09:20 UTC, trzmaxim commented on web/src/components/shared/Ads/Board.tsx
> +    type: isSeoType(seoType) ? seoTypeToAd[seoType] : DEFAULT_FILTER.type,
Понял

2022-05-27 09:20 UTC, trzmaxim approved these changes

2022-05-27 09:34 UTC, merged