feat: p2p trade flow [#181865646]
bitzlato/baseapp pull request #564
Opened 2022-06-03 09:59 UTC by velsamm

2022-06-22 12:44 UTC, velsamm commented on web/src/components/shared/Trade/TradeHistory.tsx
> +      backgroundColor={isMobileDevice ? 'transparent' : 'tradeHistoryBackground'}
лишнее условие

2022-06-22 12:51 UTC, velsamm commented on web/src/components/shared/Trade/TradePartnerShort.tsx
> +        <Box as="span">{isOnline ? t('trader.block.online') : t('trader.block.offline')}</Box>
ключи локализации неверные

2022-06-22 13:01 UTC, velsamm commented on web/src/components/shared/Trade/mobile/TradeInfo.tsx
> +                  value: '0%',
выяснить что это за проценты. я так и не понял

2022-06-22 13:07 UTC, velsamm commented on web/src/hooks/data/useFetchTrade.ts
> +// export function useFetchTrade<T extends Trade>(
удалить мусорные комменты

2022-06-22 13:09 UTC, velsamm commented on web/src/lib/socket/websocketMessageHandler.ts
> +      mutate(`${p2pUrl()}/trade/${tradeId}/chat/`);
добавить обработку нотификаций новых сообщений от админа в споре

2022-06-22 13:17 UTC, velsamm commented on web/src/screens/p2p/Trade/Trade.tsx
> +  const handleTradeDetails = (details: string, onSuccess?: () => void) => {
useCallback

2022-06-22 13:25 UTC, trzmaxim requested changes

2022-06-22 13:31 UTC, velsamm commented on web/src/components/ui/Spinner.css.ts
> +]);
регулировка в компоненте не работает нормально, если указать ```
sprinkles({
    width: '5x',
    height: '5x',
  }),
```

если убрать это, то регулировка работает нормально

2022-06-22 13:33 UTC, velsamm commented on web/src/hooks/data/useFetchP2PUser.ts
> +};
уже нет. он чудесным образом остался после ребейза. удалю

2022-06-22 15:00 UTC, trzmaxim commented on web/src/screens/p2p/Trade/Trade.tsx
> +  const handleTradeAction = (action: TradeAvailableAction) => {
Если ты React.memo не используешь, то useCallback не нужен

2022-06-22 15:02 UTC, trzmaxim commented on web/src/components/ui/Spinner.css.ts
> +]);
Без этих изменений `<Spinner size="5x" />` не сработает разве?

2022-06-23 14:50 UTC, velsamm commented on web/src/components/Stepper/Stepper.css.ts
> +};
fixed

2022-06-23 14:50 UTC, velsamm commented on web/src/components/Stepper/Stepper.tsx
> +    console.log('Stepper requires steps!');
fixed

2022-06-23 14:51 UTC, velsamm commented on web/src/components/TextInputCustom/TextInputCustom.tsx
> +        placeholder=" "
не знаю. не доглядел видимо. убрал

2022-06-23 14:52 UTC, velsamm commented on web/src/components/shared/Trade/TradeChat.tsx
> +  const isDispute = useMemo(() => trade.status === TradeStatus.DISPUTE, [trade.status]);
fixed

2022-06-23 14:53 UTC, velsamm commented on web/src/components/shared/Trade/TradePartnerShort.tsx
> +      </Box>
fixed

2022-06-23 14:58 UTC, velsamm commented on web/src/components/ui/Spinner.css.ts
> +]);
не сработает

2022-06-23 14:59 UTC, velsamm commented on web/src/components/ui/Spinner.css.ts
> +]);
пока оставляю свои изменения

2022-06-23 15:00 UTC, velsamm commented on web/src/components/shared/Trade/TradeInfo.tsx
> +          <Box maxWidth="fit-content">
убрал :)

2022-06-23 15:20 UTC, velsamm commented on web/src/screens/p2p/Trade/Trade.tsx
> +  const handleTradeAction = (action: TradeAvailableAction) => {
не понял про React.memo.
я зря натыкал useCallback'ов (и useMemo'ов) ?

2022-06-24 09:16 UTC, velsamm commented on web/src/components/shared/Trade/TradeHistory.tsx
> +      backgroundColor={isMobileDevice ? 'transparent' : 'tradeHistoryBackground'}
не лишнее

2022-06-24 09:17 UTC, velsamm commented on web/src/components/shared/Trade/TradePartnerShort.tsx
> +        <Box as="span">{isOnline ? t('trader.block.online') : t('trader.block.offline')}</Box>
не актуально

2022-06-24 09:38 UTC, velsamm commented on web/src/components/shared/Trade/mobile/TradeChat/TradeChat.tsx
> +        <Box as="span">{isOnline ? t('trader.block.online') : t('trader.block.offline')}</Box>
fixed

2022-06-24 09:49 UTC, trzmaxim commented on web/src/screens/p2p/Trade/Trade.tsx
> +  const handleTradeAction = (action: TradeAvailableAction) => {
Вот ты передаёшь handleTradeAction куда-то в компонент, если тот компонент не обернут в React.memo, то он будет всегда рендерится, в не зависимости от того использовал ты useCallback или нет.

useCallback тебе нужно использовать тогда, когда ты используешь эту функцию в useEffect или передаешь в компонент завернутый в React.memo

2022-06-24 09:55 UTC, trzmaxim commented on web/src/components/ui/Spinner.css.ts
> +]);
Я тут использую https://github.com/bitzlato/baseapp/blob/master/web/src/components/shared/Ads/Ads.tsx#L129 работает нормально. Можешь понять почему?

2022-06-24 11:32 UTC, velsamm commented on web/src/components/shared/Trade/TradeState.tsx
> +      { key: '1', content: <Box as="span">1</Box>, isCompleted: true },
fixed

2022-06-24 11:49 UTC, velsamm commented on web/src/components/shared/Trade/TradeChat.tsx
> +  const disputeLabel = useMemo(() => <DisputeLabel label={t('trade.chat.dispute.label')} />, [t]);
в этом компоненте получается всю мемоизацию можно убрать?

2022-06-24 11:56 UTC, trzmaxim commented on web/src/components/shared/Trade/TradeChat.tsx
> +  const disputeLabel = useMemo(() => <DisputeLabel label={t('trade.chat.dispute.label')} />, [t]);
да

2022-06-24 11:58 UTC, velsamm commented on web/src/components/ui/Spinner.css.ts
> +]);
посмотрю

2022-06-27 08:47 UTC, velsamm commented on web/src/components/shared/Trade/mobile/TradeInfo.tsx
> +                    Условия торговли
fixed

2022-06-27 08:48 UTC, velsamm commented on web/src/components/shared/Trade/TradeChat.tsx
> +  const disputeLabel = useMemo(() => <DisputeLabel label={t('trade.chat.dispute.label')} />, [t]);
fixed

2022-06-27 08:48 UTC, velsamm commented on web/src/components/shared/Trade/types.ts
> +import { SharedTranslateFn } from '../sharedI18n';
fixed

2022-06-27 08:50 UTC, velsamm commented on web/src/components/shared/Trade/types.ts
> +export interface IUserInfo extends UserInfo {}
типо  I - интерфейс.
т.к. интерфейс IUserInfo лишний, убрал. использовал UserInfo

2022-06-27 08:51 UTC, velsamm commented on web/src/components/shared/Trade/TradeContext.ts
> +  return (action: TradeAvailableAction) => handleTradeAction(action);
можно и так

2022-06-27 08:57 UTC, velsamm commented on web/src/components/shared/Trade/TradeModals/TradeConfirmReceiveMoneyModal.tsx
> +  };
предложенный вариант не пойдет. т.к. при закрытии модалки (если нажать просто на крестик), запрос о подтверждении оплаты улетит в бекенд. 
если пользователь еще не получил деньги за сделку, то монеты отправятся партнеру по сделке

2022-06-27 08:59 UTC, velsamm commented on web/src/components/shared/Trade/TradeModals/TradeConfirmReceiveMoneyModal.tsx
> +  };
fixed

2022-06-27 09:00 UTC, velsamm commented on web/src/components/shared/Trade/TradeModals/TradeTipsModal.tsx
> +  const balance = useMemo(() => p2pWallet?.balance, [p2pWallet]);
fixed

2022-06-27 09:00 UTC, velsamm commented on web/src/components/shared/Trade/TradeModals/TradeTipsModal.tsx
> +  const cryptocurrency = useMemo(() => trade.cryptocurrency.code, [trade.cryptocurrency.code]);
fixed

2022-06-27 09:05 UTC, velsamm commented on web/src/components/shared/Trade/TradeHistory.tsx
> +  const date = (timestamp: string) => localeDate(timestamp, 'literalFullDate');
там же таймзона автоматом угадывается

2022-06-27 09:45 UTC, velsamm commented on web/src/hooks/data/useFetchPaymethod.ts
> +      errorRetryCount: 0,
убрал errorRetryCount

2022-06-27 11:11 UTC, velsamm commented on web/src/components/shared/Trade/TradeHistory.tsx
> +  const date = (timestamp: string) => localeDate(timestamp, 'literalFullDate');
done

2022-06-27 11:16 UTC, velsamm commented on web/src/components/shared/Trade/mobile/TradeInfo.tsx
> +                  value: '0%',
это надпись для тейкеров (то есть для тех, кто откликается на объявление). оставляю как есть

2022-06-27 11:25 UTC, velsamm commented on web/src/lib/socket/websocketMessageHandler.ts
> +      mutate(`${p2pUrl()}/trade/${tradeId}/chat/`);
done

2022-06-27 12:38 UTC, trzmaxim approved these changes

2022-06-27 12:40 UTC, merged