Feat/adverts page 181865657
bitzlato/baseapp pull request #571
Opened 2022-06-09 20:02 UTC by YuriFA

2022-07-29 11:46 UTC, trzmaxim requested changes

2022-07-29 11:46 UTC, trzmaxim commented on web/src/components/shared/UserAds/ChooseRate.tsx
> +        return (
Результат этой функции выдели в компонент, например `<ChooseRateVariant />`
И вместо 
```ts
{rateVariants.map(({ title, value }) => {
...
})}
``` 
делаешь
```ts
<ChooseRateVariant title={t('Fixed rate')} value="fixed" ... />
<ChooseRateVariant title={t('Floating rate')} value="floating" ... />
```

2022-07-29 11:46 UTC, trzmaxim commented on web/src/components/shared/UserAds/ChooseRate.tsx
> +              {value === 'fixed' ? (
```suggestion
              {value === 'fixed' && (
```
Замечаю у тебя по коду, то `condition && <Component />`, то `condition ? <Component /> : null`
Старайся делать в одном стиле, хотя бы в пределах одного файла

2022-07-29 11:46 UTC, trzmaxim commented on web/src/components/shared/UserAds/UserAds.tsx
> +  const alerts =
А давай в отдельный компонент выделим :)

2022-07-29 11:46 UTC, trzmaxim commented on web/src/components/shared/UserAds/UserAdsFilter.tsx
> +  );
То что обёрнуто в useMemo ничего не даёт

2022-07-29 11:46 UTC, trzmaxim commented on web/src/hooks/data/useUserAds.ts
> +// ): UserAdvert['statusExtended'] {
с этим что планируем делать?

2022-07-29 11:46 UTC, trzmaxim commented on web/src/theme/sprinkles.css.ts
> -    flexDirection: ['row', 'column', 'row-reverse', 'column-reverse'],
А что даёт? :)

2022-07-29 11:50 UTC, YuriFA commented on web/src/theme/sprinkles.css.ts
> -    flexDirection: ['row', 'column', 'row-reverse', 'column-reverse'],
```
justifyContent?: BoxProps['justifyContent'];
```

можно так определять пропсы, а не вручную ставить все варианты

2022-07-29 11:51 UTC, YuriFA commented on web/src/theme/sprinkles.css.ts
> -    flexDirection: ['row', 'column', 'row-reverse', 'column-reverse'],
В SwitchField как раз добавил

2022-07-29 12:00 UTC, trzmaxim commented on web/src/theme/sprinkles.css.ts
> -    flexDirection: ['row', 'column', 'row-reverse', 'column-reverse'],
Ок, тогда в соседние свойства тоже добавь `as const`

2022-07-29 12:14 UTC, YuriFA commented on web/src/theme/sprinkles.css.ts
> -    flexDirection: ['row', 'column', 'row-reverse', 'column-reverse'],
Добавил в свойства которые в виде массива

2022-07-29 13:25 UTC, YuriFA commented on web/src/components/shared/UserAds/ChooseRate.tsx
> +        return (
Сделал, так имел ввиду или content prop лишний?

2022-07-29 13:25 UTC, YuriFA commented on web/src/components/shared/UserAds/UserAds.tsx
> +  const alerts =
Выделил

2022-07-29 13:25 UTC, YuriFA commented on web/src/components/shared/UserAds/UserAdsFilter.tsx
> +  );
убрал

2022-07-29 13:26 UTC, YuriFA commented on web/src/hooks/data/useUserAds.ts
> +// ): UserAdvert['statusExtended'] {
убрал, в случае если бы показывали ошибку прям в таблице, такое преобразование статуса понадобилось бы
но это убрали

2022-07-29 14:03 UTC, trzmaxim commented on web/src/components/shared/UserAds/ChooseRate.tsx
> +        return (
вместо сontent можно children использовать

2022-07-29 14:50 UTC, YuriFA commented on web/src/components/shared/UserAds/ChooseRate.tsx
> +        return (
готово

2022-08-01 07:33 UTC, trzmaxim approved these changes
👍

2022-08-01 08:24 UTC, merged