Fix/trades page filter 181865666
bitzlato/baseapp pull request #586
Opened 2022-06-23 12:39 UTC by YuriFA

- фиксы по дате в фильтре

2022-06-23 12:40 UTC, YuriFA commented on web/src/components/shared/Trades/TradesFilter.tsx
> +        calendarProps={{ maxDate: new Date() }}
мб вынести за компонент этот объект?

2022-06-24 09:37 UTC, trzmaxim requested changes

2022-06-24 09:37 UTC, trzmaxim commented on web/src/components/shared/Trades/TradesFilter.tsx
> +        calendarProps={{ maxDate: new Date() }}
тут может быть `minDate: dateFrom`?

2022-06-24 11:19 UTC, YuriFA commented on web/src/components/TextInputCustom/TextInputCustom.tsx
> +  placeholder = ' ',
Для того чтобы **:placeholder-shown** в CSS сработал

2022-06-24 11:20 UTC, YuriFA commented on web/src/components/shared/Trades/TradesFilter.tsx
> +        calendarProps={{ maxDate: new Date() }}
👍

2022-06-24 11:35 UTC, trzmaxim approved these changes
👍

2022-06-29 07:55 UTC, merged