feature: view advert, start trade [#181997699]
bitzlato/baseapp pull request #600
Opened 2022-06-30 09:15 UTC by velsamm

2022-06-30 09:16 UTC, velsamm commented
не сделана модалка с информацией о разнице курса более 20% (нет дизайна еще)

2022-06-30 09:26 UTC, trzmaxim requested changes

2022-06-30 09:26 UTC, trzmaxim commented on web/src/components/TextInputCustom/TextInputCustom.css.ts
> +export const noResize = style([input, { resize: 'none' }]);
Думаю, это плохая практика, пусть пользователь как хочет так и растягивает у себя в браузере.

2022-06-30 09:31 UTC, velsamm commented on web/src/components/TextInputCustom/TextInputCustom.css.ts
> +export const noResize = style([input, { resize: 'none' }]);
![image](https://user-images.githubusercontent.com/36211319/176643552-d3b74529-fa14-47ae-a08f-a4b054472fed.png)
ну не знаю :)

2022-06-30 09:31 UTC, trzmaxim requested changes

2022-06-30 09:31 UTC, trzmaxim commented on web/src/hooks/data/useFetchP2PWallets.ts
> +export function useFetchP2PWallet(cryptoCurrency: string | undefined) {
```suggestion
export function useFetchP2PWallet(cryptoCurrency?: string | undefined) {
```

2022-06-30 09:31 UTC, trzmaxim commented on web/src/hooks/data/useFetchTrade.ts
> +export function useFetchLastRequisites(paymethodId: number | undefined) {
```suggestion
export function useFetchLastRequisites(paymethodId?: number | undefined) {
```

2022-06-30 09:31 UTC, velsamm commented on web/src/components/TextInputCustom/TextInputCustom.css.ts
> +export const noResize = style([input, { resize: 'none' }]);
не хватает смайлика гарольда

2022-06-30 09:32 UTC, trzmaxim commented on web/src/components/TextInputCustom/TextInputCustom.css.ts
> +export const noResize = style([input, { resize: 'none' }]);
Сделай так чтобы строки в правой колонке не растягивались так

2022-06-30 09:40 UTC, YuriFA commented on web/src/theme/sprinkles.css.ts
> +    top: [0, '25%', '50%', '65%', '88%'],
Так вариантов очень много будет, если каждый кейс добавлять

Кажется лучше в style({ top: V }) записать

2022-06-30 09:53 UTC, velsamm commented on web/src/components/TextInputCustom/TextInputCustom.css.ts
> +export const noResize = style([input, { resize: 'none' }]);
fixed

2022-06-30 09:53 UTC, velsamm commented on web/src/hooks/data/useFetchP2PWallets.ts
> +export function useFetchP2PWallet(cryptoCurrency: string | undefined) {
fixed

2022-06-30 09:53 UTC, velsamm commented on web/src/hooks/data/useFetchTrade.ts
> +export function useFetchLastRequisites(paymethodId: number | undefined) {
fixed

2022-06-30 09:53 UTC, velsamm commented on web/src/theme/sprinkles.css.ts
> +    top: [0, '25%', '50%', '65%', '88%'],
вынес в стили компонента

2022-06-30 10:04 UTC, YuriFA commented on web/src/components/shared/Ads/Ad.css.ts
> +export const input = style({ '::placeholder': { color: vars.colors.inputPlaceholder } });
Это стоит прям в TextInputCustom закинуть

2022-06-30 10:15 UTC, velsamm commented on web/src/components/shared/Ads/Ad.css.ts
> +export const input = style({ '::placeholder': { color: vars.colors.inputPlaceholder } });
done

2022-06-30 10:19 UTC, YuriFA approved these changes

2022-06-30 10:29 UTC, trzmaxim requested changes

2022-06-30 10:29 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +import * as s from 'web/src/components/shared/Modal/TradeDetailsModal.css';
не надо так, у компонента должна быть одна зависимость от `.css` файла
а вот в `.css` можешь делать зависимости от других `.css`

2022-06-30 10:29 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +import * as adStyle from 'web/src/components/shared/Ads/Ad.css';
```suggestion
import * as adStyle from './Ad.css';
```
Файл соседний, не нужно использовать абсолютный путь

2022-06-30 10:29 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +      setError(errBlock);
В состоянии нужно хранить причину, а рендерить блок вне коллбека

2022-06-30 10:29 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +    300,
сделай константу

2022-06-30 10:29 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +  const navigate = (url: string) => history.push(url);
Давай использовать сразу `history.push`

2022-06-30 10:37 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +import * as s from 'web/src/components/shared/Modal/TradeDetailsModal.css';
вот так в css файле?

```
import * as detailsStyle from 'web/src/components/shared/Modal/TradeDetailsModal.css';

export const adDetailsStyle = detailsStyle;
```

2022-06-30 10:39 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +import * as s from 'web/src/components/shared/Modal/TradeDetailsModal.css';
`export * from 'web/src/components/shared/Modal/TradeDetailsModal.css';`
так сработает? 
а может в отдельный компонент выделить отображение деталей?

2022-06-30 10:45 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +import * as s from 'web/src/components/shared/Modal/TradeDetailsModal.css';
думаю не стоит выделять. этот компонент больше нигде не будет переиспользоваться

2022-06-30 10:47 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +import * as s from 'web/src/components/shared/Modal/TradeDetailsModal.css';
хотя можно и отделить. и использовать в компоненте проведения сделки

2022-06-30 10:50 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +  const navigate = (url: string) => history.push(url);
done

2022-06-30 10:52 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +  const navigate = (url: string) => history.push(url);
done

2022-06-30 10:52 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +      setError(errBlock);
done

2022-06-30 10:52 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +import * as adStyle from 'web/src/components/shared/Ads/Ad.css';
done

2022-07-01 10:26 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +import * as s from 'web/src/components/shared/Modal/TradeDetailsModal.css';
сделал отдельный компонент для ввода реквизитов

2022-07-01 12:25 UTC, trzmaxim approved these changes
lgtm

2022-07-01 14:56 UTC, merged