Feat/adverts create page [#181865659]
bitzlato/baseapp pull request #605
Opened 2022-07-04 15:54 UTC by YuriFA

2022-07-21 18:47 UTC, trzmaxim requested changes

2022-07-21 18:47 UTC, trzmaxim commented on web/src/components/shared/CreateAd/CreateAdFormStep.tsx
> +    const resizeObserver = new MutationObserver(calcHeight);
Вместо события resize можешь resizeObserver использовать
```suggestion
    const resizeObserver = new MutationObserver(calcHeight);
    resizeObserver.observe(document.body)
```

2022-07-21 18:47 UTC, trzmaxim commented on web/src/components/shared/CreateAd/CreateAdFormStep.tsx
> +    }
чтобы всё в одном стиле было
```suggestion
    const calcHeight = () => setHeight(contentRef.current?.scrollHeight);
```

2022-07-21 18:47 UTC, trzmaxim commented on web/src/components/shared/CreateAd/CreateAdFormStep.tsx
> +  isNext?: boolean;
```suggestion
  title?: ReactNode | undefined;
  children?: ReactNode | undefined;
  activeValue?: ReactNode | undefined;
  isActive?: boolean | undefined;
  isCompleted?: boolean | undefined;
  isCompletedBeforeActive?: boolean | undefined;
  isNext?: boolean | undefined;
```

2022-07-21 18:47 UTC, trzmaxim commented on web/src/components/shared/CreateAd/CreateAdFormContext.tsx
> +  createError: null | CreateError;
По названию словно функция, а на деле объект

2022-07-21 18:47 UTC, trzmaxim commented on web/src/components/shared/CreateAd/StepRate.tsx
> +export const StepRate = ({ onSubmit }: Props) => {
```suggestion
export const StepRate: FC<Props> = ({ onSubmit }) => {
```

2022-07-21 18:47 UTC, trzmaxim commented on web/src/components/shared/CreateAd/StepTerms.tsx
> +  console.log({ errors });
```suggestion
```

2022-07-21 18:47 UTC, trzmaxim commented on web/src/components/shared/CreateAd/StepType.tsx
> +export const StepType = ({ onSubmit }: Props) => {
```suggestion
export const StepType: FC<Props> = ({ onSubmit }) => {
```

2022-07-21 18:47 UTC, trzmaxim commented on web/src/components/shared/UserAds/UserAds.tsx
> +  const handleGoToCrateAnotherAd = () => {
```suggestion
  const handleGoToCreateAnotherAd = () => {
```

2022-07-21 18:47 UTC, trzmaxim commented on web/src/hooks/data/useFetchP2PPaymethods.tsx
> +  cryptocurrency: string | null;
На данном уровне лучше `undefined` использовать

```suggestion
  type?: AdvertType | undefined;
  currency?: string | undefined;
  cryptocurrency?: string | undefined;
```

2022-07-25 07:22 UTC, trzmaxim requested changes

2022-07-25 07:22 UTC, trzmaxim commented on web/src/components/form/Checkbox.tsx
> +    <Box as="label" display="inline-flex" cursor="pointer" className={s.checkbox}>
`Box` нужен? `s.checkbox` все эти свойства содержит

2022-07-25 07:45 UTC, YuriFA commented on web/src/components/form/Checkbox.tsx
> +    <Box as="label" display="inline-flex" cursor="pointer" className={s.checkbox}>
убрал

2022-07-25 07:48 UTC, YuriFA commented on web/src/components/shared/CreateAd/CreateAdFormStep.tsx
> +    const resizeObserver = new MutationObserver(calcHeight);
Что то оно плохо работало на document.body, не стал менять

2022-07-25 07:52 UTC, trzmaxim commented on web/src/components/shared/CreateAd/CreateAdFormStep.tsx
> +    const resizeObserver = new MutationObserver(calcHeight);
тогда debounce нужен на хедлер

2022-07-25 14:24 UTC, YuriFA commented on web/src/components/shared/CreateAd/CreateAdFormStep.tsx
> +    const resizeObserver = new MutationObserver(calcHeight);
Добавил

2022-07-25 14:25 UTC, YuriFA commented
@trzmaxim ui/Card ререндериться полностью когда ресайзишь до мобилки или наоборот, в случае формы она сбрасывается, это ок?

2022-07-25 15:22 UTC, trzmaxim commented
@YuriFA ты про это поведение?
https://github.com/bitzlato/baseapp/blob/master/web/src/components/ui/Card.tsx#L37

2022-07-25 15:24 UTC, YuriFA commented
> @YuriFA ты про это поведение? https://github.com/bitzlato/baseapp/blob/master/web/src/components/ui/Card.tsx#L37

да

2022-07-25 15:30 UTC, trzmaxim commented
Надо вынести это поведение из компонента, ща сделаю

2022-07-26 09:25 UTC, trzmaxim approved these changes

2022-08-01 09:36 UTC, merged