Feature/ask rate diff 20 percent 182619317
bitzlato/baseapp pull request #607
Opened 2022-07-05 12:19 UTC by velsamm

2022-07-05 20:30 UTC, trzmaxim requested changes

2022-07-05 20:30 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +};
```suggestion
const calculatePercentageDiff = (prevRate: Money, nextRate: Money): number => nextRate.amount.div(prevRate.amount).sub(1).times(100).toNumber();
```
Так будет лучше, над названием можно ещё подумать :)

2022-07-05 20:30 UTC, trzmaxim commented on web/src/components/shared/Ads/RateDiffModal.tsx
> +  mode = 'changeRate',
Лучше сделай два компонента в итоге.
Один компонент оставь `ConfirmRateChangeModal`
Второй сделай `ConfirmDangerRateModal`
И общий `ConfirmModal`

```
export const ConfirmModal = ({
  title,
  children,
  onConfirm,
  onClose,
}) => {
  const t = useSharedT();

  return (
    <Modal show onClose={onClose}>
      <ModalHeader center>{title}</ModalHeader>
      <ModalBody>{children}</ModalBody>
      <Box display="flex" alignItems="center" px="6x" py="4x">
        <Button color="secondary" variant="outlined" fullWidth onClick={onClose}>
          {t('Cancel')}
        </Button>
        <Box w="4x" flexShrink={0} />
        <Button color="secondary" fullWidth onClick={onConfirm}>
          {t('Confirm')}
        </Button>
      </Box>
    </Modal>
  );
};
```

```
export const ConfirmRateChangeModal = ({ prevRate, nextRate, ... }) => {
  ...
  return <ConfirmModal title={t('Attention!')}>
<DiffRate
        prevRate={prevRate}
        nextRate={nextRate}
        cryptoCurrency={cryptoCurrency}
        isBuy={isBuy}
      /></ConfirmModal>
}

```
```
export const ConfirmRateChangeModal = ({ prevRate, nextRate, ... }) => {
  ...
  return <ConfirmModal title={t('trade.start.diff.exchage.header')}>
<DiffExchangeRate
        prevRate={prevRate}
        nextRate={nextRate}
        cryptoCurrency={cryptoCurrency}
        isBuy={isBuy}
      /></ConfirmModal>
}

```

2022-07-06 08:35 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +};
чет я не доглядел toNumber() в пакете

2022-07-06 08:43 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +};
может просто percentageDiff?

2022-07-06 08:51 UTC, velsamm commented on web/src/components/shared/Ads/RateDiffModal.tsx
> +  mode = 'changeRate',
может общий назвать ConfirmRateModal? чтобы понятно было, что это про подтверждение курса

2022-07-06 09:05 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +};
У функции должно быть действие в названии https://github.com/kettanaito/naming-cheatsheet#ahclc-pattern

2022-07-06 09:11 UTC, trzmaxim approved these changes
👍

2022-07-06 09:12 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +};
не нужно думать над названием функции, если ее нет :)

2022-07-06 09:12 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +};
а гайдик хороший

2022-07-06 09:17 UTC, merged