fix: Some improvements to P2P trading flow [#181865646]
bitzlato/baseapp pull request #622
Opened 2022-07-13 09:14 UTC by velsamm

2022-07-28 15:02 UTC, velsamm commented on web/src/components/collapsibleBox/CollapsibleBox.css.ts
> -  maxHeight: '25em',
@trzmaxim не помнишь, была ли какая-то причина 25em ставить?

2022-07-29 12:46 UTC, trzmaxim requested changes

2022-07-29 12:46 UTC, trzmaxim commented on web/src/components/shared/Trade/Trade.tsx
> +        ).toFormat({ maxFractionDigits: 8 }),
Тоже нужно `getFormatOptionsByLanguage`.
А почему в строку переводишь? Не проще в Money оставить?

2022-07-29 12:46 UTC, trzmaxim commented on web/src/components/shared/Trade/TradeCurrencies.tsx
> +}> = ({ title, amount, code, icon = null }) => {
```suggestion
interface CurrencyProps {
  title: string;
  amount: string;
  code: string;
  icon?: ReactNode;
}

const Currency: FC<CurrencyProps> = ({ title, amount, code, icon = null }) => {
```

2022-07-29 12:46 UTC, trzmaxim commented on web/src/components/shared/Trade/TradeFeedback.tsx
> +  const handleActionTips = () => {
```suggestion
  const handleTipsClick = () => {
```

2022-07-29 12:47 UTC, trzmaxim commented on web/src/components/collapsibleBox/CollapsibleBox.css.ts
> -  maxHeight: '25em',
Я не знаю зачем :)

2022-07-31 17:58 UTC, velsamm commented on web/src/components/shared/Trade/Trade.tsx
> +        ).toFormat({ maxFractionDigits: 8 }),
мне нужна именно строка

2022-07-31 17:59 UTC, velsamm commented on web/src/components/shared/Trade/TradeCurrencies.tsx
> +}> = ({ title, amount, code, icon = null }) => {
почему именно ReactNode, а не JSX.Element?

2022-08-01 07:42 UTC, trzmaxim commented on web/src/components/shared/Trade/TradeCurrencies.tsx
> +}> = ({ title, amount, code, icon = null }) => {
Он больше сюда подходит

2022-08-01 07:51 UTC, velsamm commented on web/src/components/shared/Trade/TradeFeedback.tsx
> +  const handleActionTips = () => {
done

2022-08-01 07:52 UTC, trzmaxim approved these changes

2022-08-01 10:31 UTC, merged