Feat/new gift page 182761069
bitzlato/baseapp pull request #629
Opened 2022-07-20 17:55 UTC by YuriFA

2022-07-29 13:42 UTC, trzmaxim approved these changes
👍 Я не осилил

2022-07-29 13:42 UTC, trzmaxim commented on web/src/components/Gifts/DeletedGiftModal.tsx
> +export const DeletedGiftModal = ({ gift, onClose }: Props) => {
```suggestion
export const GiftDeletedModal = ({ gift, onClose }: Props) => {
```

2022-07-29 13:42 UTC, trzmaxim commented on web/src/screens/GiftsScreen/HistoryGiftsScreen.css.ts
> +]);
```suggestion
export const tabText = sprinkles({
    fontSize: 'small',
    fontWeight: 'strong',
    pb: '3x',
  });
```

2022-07-29 13:42 UTC, trzmaxim requested changes
а стоп

2022-07-29 13:50 UTC, trzmaxim requested changes

2022-07-29 13:50 UTC, trzmaxim commented on web/src/components/ui/Button.tsx
> +          className,
В это уже все разработчики потыкались 😬

У компонента есть вариативность в `variant`, значит варианты заранее определены и ограничены. Если мы добавляем `className` то вариантов может быть бесконечное множество – и как такое поддерживать? Мы стремимся к системности, а `className` это хаус. Убери плиз 🙏

Если там что-то не преодолимое, то напиши что нужно сделать  – подумаем как это встроить в систему.

2022-07-29 13:53 UTC, YuriFA commented on web/src/components/ui/Button.tsx
> +          className,
Да тут простая ситуация, в дизайне отрисовывают кнопки нестандартной ширины (не по заданным паддингам)
И чтобы было проще добавить стиль `minWidth: Xpx` - добавил это

уберу, тк решаемо заданием fullWidth + контейнером с шириной

2022-07-29 14:40 UTC, YuriFA commented on web/src/assets/svg/CopyIcon.svg
> +<rect x="5.16602" y="8.1665" width="10.8333" height="10.8333" rx="2.5" fill="#B3B8BF"/>
добавил

2022-07-29 14:40 UTC, YuriFA commented on web/src/screens/GiftsScreen/HistoryGiftsScreen.css.ts
> +]);
поправил

2022-07-29 14:40 UTC, YuriFA commented on web/src/components/ui/Button.tsx
> +          className,
готово

2022-08-01 07:37 UTC, trzmaxim approved these changes
💯

2022-08-02 06:58 UTC, merged