fix issues in View Advert / Start Trade [181997699]
bitzlato/baseapp pull request #648
Opened 2022-08-03 08:42 UTC by velsamm

2022-08-08 08:33 UTC, trzmaxim requested changes

2022-08-08 08:33 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +const WarningBlockMobile: FC<{ unactiveReason: string }> = ({ unactiveReason }) => (
```suggestion
interface WarningBlockMobileProps {
  unactiveReason: string
}

const WarningBlockMobile: FC<WarningBlockMobileProps> = ({ unactiveReason }) => (
```

2022-08-08 08:33 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +  const isLogged = !!user;
```suggestion
  const isLogged = user !== undefined;
```

2022-08-08 08:33 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +      maxFractionDigits: fieldType === 'cryptocurrency' ? 8 : 0,
```suggestion
      maxFractionDigits: fieldType === 'cryptocurrency' ? cryptoCcy.minorUnit : 0,
```

2022-08-08 08:33 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +      const cMin = advert[limitType].min;
`lcMax` `cMax` `cMin` что эти имена значат? Думаю сокращения не очень удачные

2022-08-08 08:33 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +          return v.toFormat({ ...getFormatOptionsByLanguage(lang), maxFractionDigits: 8 });
```suggestion
          return v.toFormat({ ...getFormatOptionsByLanguage(lang), maxFractionDigits: cryptoCcy.minorUnit });
```

2022-08-08 08:33 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +        return <WarningBlockMobile unactiveReason={reason} />;
```suggestion
        return <WarningBlockMobile>{reason}</WarningBlockMobile>;
```

2022-08-08 08:33 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +const WarningBlockMobile: FC<{ unactiveReason: string }> = ({ unactiveReason }) => (
Можно `children` использовать. Это хорошая практика

```suggestion
const WarningBlockMobile: FC = ({ children }) => (
```

2022-08-08 08:33 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +  const actionBlock = () => {
Не нужно делать функции для рендера в компоненте, выдели в отдельный компонент.

2022-08-08 08:33 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +  const actionBlock = () => {
Либо let используй
```
let actionBlock;
if (...) {
  actionBlock = '...';
} else if (...) {
  actionBlock = '...';
} else {
  actionBlock = '...';
}
```

2022-08-08 08:33 UTC, trzmaxim commented on web/src/components/shared/Trade/TradeModals/Trade2FactorModal.tsx
> +export const Trade2FactorModal: FC = () => {
```suggestion
export const TradeTwoFactorModal: FC = () => {
```

2022-08-08 08:33 UTC, trzmaxim commented on web/src/components/shared/Trade/TradeModals/Trade2FactorModal.tsx
> +    </Text>
Это не актуально вроде, в приложении не будет такого названия :)

2022-08-08 08:41 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +  const isLogged = !!user;
а в чем принципиальная разница? 
что !!user вернет мне boolean, что user !== undefined тоже вернет boolean. а если user вдруг станет null?

2022-08-08 08:45 UTC, velsamm commented on web/src/components/shared/Trade/TradeModals/Trade2FactorModal.tsx
> +    </Text>
а что актуально? :)
подсмотрел подобный ко в WithdrawP2P.tsx

2022-08-08 08:49 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +      const cMin = advert[limitType].min;
согласен. нейминг так себе

2022-08-08 08:51 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +  const actionBlock = () => {
лучше let тогда, чтобы не плодить компонентов.

я бы вообще разделил этот компонент Ad.tsx на множество мелких компонентиков

2022-08-08 08:51 UTC, YuriFA commented on web/src/components/shared/Ads/Ad.tsx
> +      maxFractionDigits: fieldType === 'cryptocurrency' ? 8 : 0,
Вынести бы в переменную ```fieldType === 'cryptocurrency'``` - часто проверяется

2022-08-08 08:55 UTC, trzmaxim commented on web/src/components/shared/Ads/Ad.tsx
> +  const isLogged = !!user;
Не удобно читать, код усложняет, в уме нужно вычислить результат. 
`user !== undefined` – сразу понятно что исключаем.

А если вдруг будет null – это изменение типа, которое должно вести изменение кода, это добавление новой логики.

2022-08-08 08:58 UTC, trzmaxim commented on web/src/components/shared/Trade/TradeModals/Trade2FactorModal.tsx
> +    </Text>
Думаю можно без этого текста

2022-08-08 10:40 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +const WarningBlockMobile: FC<{ unactiveReason: string }> = ({ unactiveReason }) => (
done

2022-08-08 10:43 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +  const isLogged = !!user;
done

2022-08-08 10:54 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +      const cMin = advert[limitType].min;
done

2022-08-08 10:54 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +      maxFractionDigits: fieldType === 'cryptocurrency' ? 8 : 0,
done

2022-08-08 10:54 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +      maxFractionDigits: fieldType === 'cryptocurrency' ? 8 : 0,
done

2022-08-08 10:54 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +          return v.toFormat({ ...getFormatOptionsByLanguage(lang), maxFractionDigits: 8 });
done

2022-08-08 10:54 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +        return <WarningBlockMobile unactiveReason={reason} />;
done

2022-08-08 10:59 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +  const actionBlock = () => {
все-таки лучше отдельный компонент

2022-08-08 12:29 UTC, velsamm commented on web/src/components/shared/Ads/Ad.tsx
> +  const actionBlock = () => {
разделил огромный Ad на несколько мелких

2022-08-08 12:31 UTC, velsamm commented on web/src/components/shared/Trade/TradeModals/Trade2FactorModal.tsx
> +    </Text>
```
<TwoFactorModal
      show={ask2fa}
      onClose={handleClose}
      onSend={handleSend}
      buttonText={t('trade.state.button.confirm_payment')}
      // text={text}
    />
```

просто вот так без text ?

2022-08-09 10:50 UTC, trzmaxim commented on web/src/components/shared/Trade/TradeModals/Trade2FactorModal.tsx
> +    </Text>
да

2022-08-09 10:52 UTC, velsamm commented on web/src/components/shared/Trade/TradeModals/Trade2FactorModal.tsx
> +    </Text>
done

2022-08-09 10:52 UTC, velsamm commented on web/src/components/shared/Trade/TradeModals/Trade2FactorModal.tsx
> +export const Trade2FactorModal: FC = () => {
done

2022-08-09 10:54 UTC, trzmaxim approved these changes
👍

2022-08-09 10:58 UTC, YuriFA approved these changes

2022-08-09 11:00 UTC, merged