Feat/add deeplinks handler
bitzlato/baseapp pull request #664
Opened 2022-08-16 11:52 UTC by YuriFA

2022-08-16 14:03 UTC, trzmaxim requested changes

2022-08-16 14:03 UTC, trzmaxim commented on web/src/routes/Layout/index.tsx
> +      <Route key="deeplink" exact path={['/p2p/', '/p2p']} component={DeeplinkScreen} />,
А давай объединим с BoardScreen. Тогда редирект не нужно делать.
Примерно так:
```suggestion
<Route
  key="BoardScreen"
  path={['/p2p/:filter?', '/:lang/p2p/:filter?']}
  render={(props) => <><DeeplinkScreen {...props} /><BoardScreen {...props} /></>}
/>
```

2022-08-16 14:12 UTC, YuriFA commented on web/src/hooks/mutations/useActivateDeeplink.ts
> +  SHOW_WITHDRAW_VOUCHER = 'showWithdrawVoucher',
он же в **action** свойстве приходит с бэка

2022-08-16 14:13 UTC, trzmaxim commented on web/src/hooks/mutations/useActivateDeeplink.ts
> +  SHOW_WITHDRAW_VOUCHER = 'showWithdrawVoucher',
Понял, Тогда ок

2022-08-16 14:20 UTC, YuriFA commented on web/src/screens/DeepLinkScreen/DeepLinkScreen.tsx
> +        document.cookie = serializeCookie('referer_id', deeplinkCode);
убрал

2022-08-16 14:20 UTC, YuriFA commented on web/src/screens/DeepLinkScreen/DeepLinkScreen.tsx
> +          redirect(`/${lang}/p2p/`);
done

2022-08-16 14:20 UTC, YuriFA commented on web/src/screens/DeepLinkScreen/DeepLinkScreen.tsx
> +      console.log('unmount deeplink component');
убрал

2022-08-16 14:21 UTC, YuriFA commented on web/src/screens/DeepLinkScreen/DeepLinkScreen.tsx
> +        console.log('deeplink not provided');
убрал, думаю нет смысла куда то отправлять если самого параметра нет

2022-08-16 14:21 UTC, YuriFA commented on web/src/screens/DeepLinkScreen/DeepLinkScreen.tsx
> +    async function handleDeeplink() {
done

2022-08-16 14:22 UTC, YuriFA commented on web/src/routes/Layout/index.tsx
> +      <Route key="deeplink" exact path={['/p2p/', '/p2p']} component={DeeplinkScreen} />,
Давай сделаю в отдельном PR где заменю будут ссылки на p2p страницы из baseapp

2022-08-16 14:39 UTC, trzmaxim commented on web/src/screens/DeepLinkScreen/DeepLinkScreen.tsx
> +  const chpu = `${advert.type === 'selling' ? 'buy' : 'sell'}-${advert.cryptocurrency}-${
Ещё небольшое изменение нужно
```suggestion
  const seoUrl = `${advert.type === 'selling' ? 'buy' : 'sell'}-${advert.cryptocurrency}-${
```

2022-08-16 14:39 UTC, trzmaxim commented on web/src/routes/Layout/index.tsx
> +      <Route key="deeplink" exact path={['/p2p/', '/p2p']} component={DeeplinkScreen} />,
Ок

2022-08-16 14:48 UTC, YuriFA commented on web/src/screens/DeepLinkScreen/DeepLinkScreen.tsx
> +  const chpu = `${advert.type === 'selling' ? 'buy' : 'sell'}-${advert.cryptocurrency}-${
done

2022-08-18 09:02 UTC, YuriFA commented
@trzmaxim Вынес обработку диплинков в хук и перенес использование в Board

Если делать в Layout/index то там будет вызываться сразу и обработка диплинков и скрин доски. В обоих есть редиректы и пользователя будет перенаправлять несколько раз

2022-08-18 09:58 UTC, trzmaxim approved these changes

2022-09-12 10:53 UTC, merged