fix: Catch max file size error on change avatar [#183852422]
bitzlato/baseapp pull request #791
Opened 2022-11-23 09:56 UTC by YuriFA

2022-11-23 11:42 UTC, trzmaxim requested changes

2022-11-23 11:42 UTC, trzmaxim commented on web/src/helpers/fetch.ts
> +function isJSON(str: string) {
```suggestion
const isJSON = (str: string) => {
```

Сделай плиз такой стиль

2022-11-23 11:42 UTC, trzmaxim commented on web/src/helpers/fetch.ts
> +      const { errors, error, ...rest } = (text && isJSON(text) ? JSON.parse(text) : {}) as any;
А может тут лучше не проверку делать, а сразу функцию-парсер написать

Например
```
const parse = (str) => {
 try {
    return JSON.parse(str);
  } catch (e) {
    return {};
  }
}
```

2022-11-23 11:44 UTC, YuriFA commented on web/src/helpers/fetch.ts
> +      const { errors, error, ...rest } = (text && isJSON(text) ? JSON.parse(text) : {}) as any;
А что будет делать функция-парсер?

2022-11-24 08:46 UTC, YuriFA commented on web/src/helpers/fetch.ts
> +const parseJSON = (str: string | undefined, emptyResult = {}): object => {
@trzmaxim так имел ввиду?

2022-11-24 13:00 UTC, trzmaxim commented on web/src/helpers/fetch.ts
> +const parseJSON = (str: string | undefined, emptyResult = {}): object => {
Да, только `object` лучше не использовать. `Record<string, unknown>` или что-то похожее, или `any` 😃

2022-11-24 13:05 UTC, YuriFA commented on web/src/helpers/fetch.ts
> +const parseJSON = (str: string | undefined, emptyResult = {}): object => {
поправил

2022-11-25 13:01 UTC, trzmaxim approved these changes
👍

2022-11-25 14:40 UTC, merged