Change favicon and title
bitzlato/baseapp pull request #98
Opened 2021-08-30 13:29 UTC by c0gnize

![Screenshot 2021-08-30 at 16 28 53](https://user-images.githubusercontent.com/12247182/131346690-b4a9ac01-87ac-4dc9-afb1-e9935af0cec6.png)

2021-08-30 15:28 UTC, trzmaxim requested changes
Давай добавим svg и варианты для мобильных ОС тоже  🙏
Статья про фавиконку в 2021 https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs

2021-08-31 08:17 UTC, trzmaxim requested changes

2021-08-31 08:17 UTC, trzmaxim commented on web/public/favicon.svg
> +<svg id="Слой_1" data-name="Слой 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
`id="Слой_1" data-name="Слой 1"` ? и сжать чуть можно https://jakearchibald.github.io/svgomg/

2021-08-31 08:17 UTC, trzmaxim commented on web/src/app/template.html
> +        <link rel="icon" href="/favicon.svg" type="image/svg+xml">
`<link rel="apple-touch-icon" href="/apple-touch-icon.png">` ещё нужно

2021-08-31 08:18 UTC, c0gnize commented on web/src/app/template.html
> +        <link rel="icon" href="/favicon.svg" type="image/svg+xml">
добавлю

2021-08-31 08:28 UTC, trzmaxim approved these changes
💯

2021-08-31 08:28 UTC, merged